name: study_timer
description: A simple timer to help you with your study techniques.

publish_to: 'none' 

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  circular_countdown_timer: ^0.2.0
  flutter_local_notifications: ^3.0.1+6
  duration_picker: ^1.0.1
  page_transition: ^1.1.7+6
  webview_flutter: ^2.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - images/